### PR TITLE
fix arXiv id extraction

### LINKED ISSUE #19: Cannot add a paper from arxiv
When I search for a paper on the arxiv tab (search for `A new quantum ripple-carry addition circuit`), I find the paper but when I click on `see on papernet`, I just end up on the page of one of my other papers, without having the paper added to my space

### PR DESCRIPTION
**Pull request by bejito**
closes #19

### CODE REVIEW

File: arxiv_test.go [hunk 1]
```diff
@@ -109,39 +106,30 @@ func TestArxivSpider_Import(t *testing.T) {
...
+				"sortBy":    []string{"submittedDate"},
+				"sortOrder": []string{"descending"},
+			},
 		},
-		"failing because could not extract id": {
+		"still extracts something even if invalid id": {
 			URL:            "http://arxiv.org/abs/not-an-id",
-			ExpectedParams: map[string][]string{},
-			Error:          true,
+			ExpectedParams: map[string][]string{
```
Comment (bobinette) [inline arxiv_test.go:120]: this one does not seem to be used in the tests anymore, though it would be better to actually test the output 😉 can you restore that?

**Review by bobinette — APPROVED** [review]
Merging and migrating to #23
